version = 0.1

[staging.deploy.parameters]
stack_name = "todo-list-aws"
resolve_s3 = true
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []

[staging.global.parameters]
region = "us-east-1"
